os: windows
language: go

go:
- 1.15.x

script:
- git clone --depth=50 https://github.com/emicklei/melrose.git emicklei/melrose
- ls -l
- ls -l 'C:\\tools\\msys64\mingw64\bin'
- cd emicklei/melrose/cmd/melrose
- VERSION=$(git tag | sort -V | tail -1)
- echo $VERSION
- go build -ldflags="-X 'core.BuildTag=$VERSION'"
- rm main.go
- ls -l
- cp 'C:\\tools\\msys64\mingw64\bin\libportmidi.*' .

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "public.philemonworks.com"
  skip_cleanup: true
  acl: public_read
  on:
    branch: main


before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        
        ## go install requires this
        ## choco install gpg4win

        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        
        ## https://www.devdungeon.com/content/install-gcc-compiler-windows-msys2-cc
        $msys2 pacman --noconfirm -S base-devel gcc vim cmake

        ## https://schollz.com/blog/portmidi/
        $msys2 pacman --noconfirm -S mingw-w64-x86_64-portmidi

        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it        
        ;;
    esac

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

env:
  global:
    - secure: "w4Wh/aPqXuV3S7ylGTZS4t6+5KD8jUEYo/9rRhuq9puJIbyqO1CPnN6/tHuqr2lPhZRXKX3LA1BpCtfYe4nY2B6zSBkXzuQmK98UVzA0PIbRnu4cn90LhU3TMi6njgljpiJs0r5FTfJWYnw0H50vsK/V9LNVppFnyVdtKkd3BZ86bPgYumw/Mhu9dc8nabF65PrpPDGnuWBZzq8U8SlwiN7fUc72iBvi3ySf8MMLGwupEeszBon85rxtISL9PMBhbpUrdG9A5dbUXahZlHtzEtndK4jdUxHivVz25PpnbXA1jlnOf0vwnYE/CuAe/fRJhBbr8d/12cevc30D1GYcNTuZz6110eiV77+Y4zivz/Vr3tZE06tiJ9roHFY2bMST8ab/8aQozuiss3zThUrO80EA4WYmNHhSSTq03Q+/Ip41MHqi36gWbH2wO+3B/PHgNKFVh/SJTpEY0oC1VBi5or1WvX1MGBZPyW6qb29uArmdZRLu+oF2FVCyRN7G3oK3pX/xJGWIEM6PTwOCUzFgpcNya2EiinSb6nkMMgG6tsOJvGbAXgu38DtuQs/xV+Hz5dLws2NtL8G+FnbuP66x2btaxFQTDZHL3KDWiG/93Z8RJZRN4JF3yIlvWZUplhXUHy1zofKqzcb4g0mRaEhNUYnzeXSxd8Jqo2sKfbGCMJQ="
    - secure: "x4gc+h3VdFAgZjw6v7pZMSA//uPIYrZc37yppEG53TVpoVpfHpIAVYgXxprX89H7lGr2YaOzXivyJ+BzOGqaq20S2mlNNHH5xUegtI4rQftBMkyO/x0J3tqu0kgo0mlsUUN9aXZrC0zatZlwpz6CL4Jqh7qpzvbNKHbUm2o+Re4bNbQG0paSIgst5FyuY0/n1sKyJq2U3jbxiJNtleNtatJjfKIOICgExhM8EywBpk8wEuEWOzi6yrGOqzm5PQ5lkDM9xMni5hde5prZkmeYW+2uDS6H80fTMbHkKjiKoM60y8mGCAQvCcWKStNMqffmZ6k1qniKsnMHLj0Cgv80RDGWnB+/7AmiTboCXN9jpY6lZm9pJQ6gbiQZI2xMHAeMOVlOf+KR5M+6g+FgHIqlJW8L0bQMgTM6Zq6jHVwTfaP4DvYkiW6veB9mCPDZQ5hIl6aOke+h8KU3bPZ0JAQL+oSDD6EogVdDnRDcrvFcnPKQtplevXwGH3BlVYlr+Oy7SMWBITEDJTY7NV+auvw4DgnCBO2F+389UWYjq10Ozm05vOLS9bG0uEFa4WoH2q+70f6bZ1hH8aN10zyO3NgKsure0ajUGc/KRLrZuTUUEcMDQ+lh31GzHVoR6LLIC89NM3HqBE4XzuorNbYWCK+cgl9sZ+Vu8BfiaQonvfckXGY="