os: windows
language: go

go:
- 1.15.x

script:
- git clone --depth=50 https://github.com/emicklei/melrose.git emicklei/melrose
- ls -l
- cd emicklei/melrose/cmd/melrose
- go build
- ls -l
- echo $SOMEVAR


before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        
        ## go install requires this
        ## choco install gpg4win

        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        
        ## https://www.devdungeon.com/content/install-gcc-compiler-windows-msys2-cc
        $msys2 pacman --noconfirm -S base-devel gcc vim cmake

        ## https://schollz.com/blog/portmidi/
        $msys2 pacman --noconfirm -S mingw-w64-x86_64-portmidi

        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it        
        ;;
    esac

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

env:
  global:
    secure: Y1NiR8rg3VhyGdtXfN5RU++23KQbrIVNiacaLQBBeGBcfdNdRiX+FLrpozIdCGZ7OpgovFGgHOxMkOKqIA4DftH4LVnGZyhqlsLDcfjBOZTkkWlHf1cUevNuGQi+D9NvrutOI7802zDpBRT0NWV47iHGPaBceTg9vza3flsmgAmSRXM5Pbtp2aVwjVDgg+6AJJgZZejp7L/cdJCJCX/KMRzkPuAoztGEdjrZiP3a3GHNw44CUoTWht9YO5Q4bmHj1BMNerWjapvvPf074sEfv0cANnFFg17LCwuAYWlwJXSqaTtTXDrFV5P3xpwgZwqwCdzAKyD4MdX9QffzAZNB74YILD8rFIqKeWMBgt1pg5y1f9VNDirxW1GKCOGJm8ODxmSlp7d2Pah+1VfXUpXvU+ernY+tPze46N9uumLLeYyhmtaXXSgJoDSRcf+9JIH91arMw0aOg+g5caYv3izYVDR6m41ypTKocwQ/2hm8RLEU8U3+03MVTEN6iThpYpw6FeJ0WdSqMeCjTDi+SaBrdyKqA1Pnic6jTvxm1Oxw3iNjmcE3PIRtZZBMibRB+pMMC9jqbYap6HgavZAoE85KRD89MnNbJAZJSq5huO93YelkYd7dz1mCC0xArsw0r/dD6JZjfWGgaBT8Vs8d2ky9Wdc2WAnZMJqzJOKmnw9/WMo=    