os: windows
language: go

go:
- 1.17.x

script:
- pwd 
- git clone --depth=50 https://github.com/emicklei/melrose.git emicklei/melrose
- ls -l
- ls -l 'C:\\tools\\msys64\mingw64\bin'
- cd emicklei/melrose/cmd/melrose
- VERSION=$(git tag | sort -V | tail -1)
- echo $VERSION
- TARGET=/c/Users/travis/gopath/src/github.com/emicklei/melrose-windows/target
- export CGO_CFLAGS="-IC:\\tools\msys64\mingw64\include"
- export CGO_LDFLAGS="-LC:\\tools\msys64\mingw64\lib" 
- CGO_ENABLED=1 go build -v -buildmode=exe -ldflags="-X 'main.BuildTag=$VERSION'" -o $TARGET/melrose.exe
- cp 'C:\\tools\\msys64\mingw64\bin\libgcc_s_seh-1.dll' $TARGET
- cp 'C:\\tools\\msys64\mingw64\bin\libstdc++-6.dll' $TARGET
- cp 'C:\\tools\\msys64\mingw64\bin\libwinpthread-1.dll' $TARGET
- ls -l $TARGET
- export PATH=$PATH:/c/tools/msys64/mingw64/bin
- zip -r "melrose-$VERSION.zip" .

deploy:
  provider: releases
  api_key:
    secure: "iEG/M0YI+5Kc8+VyD8IVq67NrjKlOyAk73cw/wct/sYfKJ0wNCO2BvX3DvX29hqWA8GVzh3ecmsatKAXZHtcgDuQLHjU3sm8E2MlaRAkHKBsrSCwuzKDwmpFd8VykppkQxaVT/X+l2Oua3DKvWdL9PriQ3XN6F2jmfTSLVn63OKOYgFRBEtyb6yO2kUzG/W+t4dzxhbXAvEkIdyL+L251KAlDzXngnL8Inca7qW8l5BsUF9x0Bn+Np0xHXQ2gCN7eXFM6tczXjOPcQ0Ug2+ZUPtwKqi6KPsxuYtF82kKnA0z1c9g+nCdnKanG9zm5BeliuHwGUWT+z3Gczt8wC9J1oLfp+55s5Tcq467JFMoYPjzBgZEckJb7YEiu+CnenAQWlUSr5TsvneJkPH7boXorzVQ0wqlR2i5doBGLUeiLPI2JpIAOJYV7nZNVGamYCs58D4Yu6SsxEjQEMy687/94AL++E2qq6iVJhbnsipRGVJzColIuMz2W6yO8YvrNKwa8yzBBsNCT2MT8TFCMxSXXIq4vpWDiG1nR5sMOMiygAqwyskkxfyG70hWpY/DoPJ1ghMMr2JNCCOPA+gxE2a4wg3M5OvvD5bDlNFQLjjdyk9pOhRFMkULGSagPBGD6r13ZU3685iqWL/tQyXYBq5HwUlP6/SFS7R2/4Vpq2DEOTU="
  file: "melrose-$VERSION.zip"
  skip_cleanup: true
  on:
    tags: true


before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain

        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        
        ## https://www.devdungeon.com/content/install-gcc-compiler-windows-msys2-cc
        $msys2 pacman --noconfirm -S base-devel gcc vim cmake

        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it                
        ;;
    esac

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64